# Generated by Django 2.1.3 on 2018-11-17 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_category', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='obra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insc_obra', models.CharField(max_length=20)),
                ('nome_obra', models.CharField(max_length=50)),
                ('foto_obra', models.ImageField(upload_to='obra_fotos')),
                ('category_obra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.category')),
            ],
        ),
        migrations.CreateModel(
            name='pessoa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_pessoa', models.EmailField(max_length=150, unique=True)),
                ('pessoa_votou', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='pessoaVoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_voto', models.DateTimeField(auto_now_add=True)),
                ('obra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.obra')),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.pessoa')),
            ],
        ),
        migrations.CreateModel(
            name='voto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidadeVotos', models.IntegerField()),
                ('category_obra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.category')),
                ('obraVotada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.obra')),
            ],
        ),
    ]
