# Generated by Django 2.1.3 on 2018-11-18 03:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obra',
            name='category_obra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_obra', to='website.category'),
        ),
        migrations.AlterField(
            model_name='pessoavoto',
            name='obra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='obra', to='website.obra'),
        ),
        migrations.AlterField(
            model_name='pessoavoto',
            name='pessoa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pessoa', to='website.pessoa'),
        ),
    ]
