# Generated by Django 2.1.3 on 2018-11-19 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20181118_0131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obra',
            name='nome_obra',
            field=models.CharField(max_length=300),
        ),
    ]
