# Generated by Django 2.1.3 on 2018-11-19 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20181119_0051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voto',
            name='quantidadeVotos',
            field=models.IntegerField(default=0),
        ),
    ]
