# Generated by Django 2.1.3 on 2018-11-19 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_auto_20181119_0120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voto',
            name='quantidadeVotos',
            field=models.IntegerField(),
        ),
    ]
