# Generated by Django 2.1.3 on 2018-11-19 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_auto_20181119_0143'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pessoavoto',
            name='obra',
        ),
        migrations.AddField(
            model_name='pessoavoto',
            name='obra1',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='obra1', to='website.obra'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pessoavoto',
            name='obra2',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='obra2', to='website.obra'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pessoavoto',
            name='obra3',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='obra3', to='website.obra'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pessoavoto',
            name='obra4',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='obra4', to='website.obra'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pessoavoto',
            name='obra5',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='obra5', to='website.obra'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pessoavoto',
            name='obra6',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='obra6', to='website.obra'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pessoavoto',
            name='obra7',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='obra7', to='website.obra'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pessoavoto',
            name='obra8',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='obra8', to='website.obra'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='voto',
            name='quantidadeVotos',
            field=models.IntegerField(default=0),
        ),
    ]
